name: ado-npm-auth-$(Rev:rrr)

pr: none
trigger:
  branches:
    include:
      - main
      - 'release/*'

resources:
  repositories:
  - repository: OfficePipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release

variables:
  - name: tags
    value: production,externalfacing

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux

    sdl:
      codeql:
        compiled:
          enabled: true
        runSourceLanguagesInSourceAnalysis: true

    stages:
    - stage: main
      jobs:
      - script: echo "Hello, world!"
        displayName: "Dummy script"
